"""Cloud file/data store — Emblem saves data to the cloud (Supabase) on request, lists it,
reads it back, and deletes it, from any device. Local saves go to the emblem file home; this
is the cloud half so the owner can say "save this to the cloud" / "delete that from cloud".

Uses the same `emblem_pg` Supabase connection as cloud_memory. The table is created on first
use so no manual migration is needed.
"""

from ..kernel import Tier, tool, vault

_DDL = """
create table if not exists public.cloud_files (
    id          bigint generated by default as identity primary key,
    name        text not null,
    content     text not null default '',
    kind        text not null default 'data',
    updated_at  timestamptz not null default now(),
    created_at  timestamptz not null default now()
)
"""


def _ci():
    return vault.get_secret("emblem_pg")


def _conn():
    import psycopg
    return psycopg.connect(_ci(), sslmode="require", connect_timeout=20, autocommit=True)


@tool("cloud.save", Tier.SAFE, "Save a named piece of data/file to cloud storage", network=True,
      summarize=lambda a: f"Save '{a.get('name')}' to the cloud")
def save(name="", content="", kind="data"):
    if not _ci():
        return {"ok": False, "error": "Cloud not configured (emblem_pg missing)."}
    if not (name or "").strip():
        return {"ok": False, "error": "A name is required."}
    try:
        with _conn() as conn:
            conn.execute(_DDL)
            # upsert by name (keep one current copy per name)
            conn.execute("delete from public.cloud_files where name = %s", (name,))
            conn.execute("insert into public.cloud_files (name, content, kind) values (%s, %s, %s)",
                         (name.strip(), content or "", kind or "data"))
        return {"ok": True, "name": name, "where": "cloud"}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


@tool("cloud.list", Tier.SAFE, "List files/data saved in cloud storage", network=True)
def listing():
    if not _ci():
        return {"ok": True, "items": []}
    try:
        with _conn() as conn:
            conn.execute(_DDL)
            cur = conn.execute("select name, kind, length(content) as size, updated_at "
                               "from public.cloud_files order by updated_at desc limit 200")
            rows = cur.fetchall()
        return {"ok": True, "items": [{"name": n, "kind": k, "size": s, "updated_at": u.isoformat()}
                                      for n, k, s, u in rows]}
    except Exception as exc:
        return {"ok": False, "error": str(exc), "items": []}


@tool("cloud.get", Tier.SAFE, "Read a named file/data back from cloud storage", network=True)
def get(name=""):
    if not _ci():
        return {"ok": False, "error": "Cloud not configured."}
    try:
        with _conn() as conn:
            conn.execute(_DDL)
            cur = conn.execute("select name, content, kind from public.cloud_files "
                               "where name = %s order by updated_at desc limit 1", (name,))
            row = cur.fetchone()
        if not row:
            return {"ok": False, "error": f"No cloud file named '{name}'."}
        return {"ok": True, "name": row[0], "content": row[1], "kind": row[2]}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}


@tool("cloud.delete", Tier.CAUTION, "Delete a named file/data from cloud storage", network=True,
      summarize=lambda a: f"Delete '{a.get('name')}' from the cloud")
def delete(name=""):
    if not _ci():
        return {"ok": False, "error": "Cloud not configured."}
    try:
        with _conn() as conn:
            conn.execute(_DDL)
            cur = conn.execute("delete from public.cloud_files where name = %s", (name,))
            n = cur.rowcount
        return {"ok": True, "name": name, "deleted": n}
    except Exception as exc:
        return {"ok": False, "error": str(exc)}
